package com.benzoft.countinggame.files;

import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

public final class DataFile extends AbstractFile {

    private static DataFile file;

    private int count;
    private Set<UUID> mutedPlayers;

    private DataFile() {
        super("data.yml");
    }

    @Override
    public void setDefaults() {
        setHeader("This file contains data regarding The Counting Game.",
                "Do not edit this file manually unless you know what you're doing.");
        count = (int) add("Count", 0);
        mutedPlayers = ((List<String>) add("MutedPlayers", Collections.emptyList())).stream().map(UUID::fromString).collect(Collectors.toSet());
        save();
    }

    @Override
    public void save() {
        getConfig().set("Count", count);
        getConfig().set("MutedPlayers", mutedPlayers.stream().map(UUID::toString).collect(Collectors.toList()));
        try {
            getConfig().save(getFile());
        } catch (final IOException e) {
            e.printStackTrace();
        }
    }

    public List<Player> getCGPlayers() {
        return Bukkit.getOnlinePlayers().stream().filter(player -> !mutedPlayers.contains(player.getUniqueId()) && ConfigFile.getInstance().isCGWorld(player.getWorld())).collect(Collectors.toList());
    }

    public boolean mutePlayer(final Player player) {
        return mutedPlayers.add(player.getUniqueId());
    }

    public boolean unmutePlayer(final Player player) {
        return mutedPlayers.remove(player.getUniqueId());
    }

    public int getCount() {
        return count;
    }

    public void incrementCount() {
        count++;
    }

    public static DataFile getInstance() {
        file = file == null ? new DataFile() : file;
        return file;
    }

    public static void reload() {
        file = new DataFile();
        file.setDefaults();
    }
}
